name: Lean Build Check

on:
  push:
    branches: [ main ]
    paths:
      - 'lakefile.lean'
      - 'FinLin/**'
      - 'blueprint/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lakefile.lean'
      - 'FinLin/**'
      - 'blueprint/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Lean
      run: |
        curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        source $HOME/.elan/env
        
    - name: Get cache
      run: ~/.elan/bin/lake exe cache get
      
    - name: Build project
      run: ~/.elan/bin/lake build
      
    - name: Build PDFs from LaTeX
      uses: xu-cheng/texlive-action@v2
      with:
        docker_image: ghcr.io/xu-cheng/texlive-full:20250101
        run: |
          cd blueprint/src
          latexmk -pdf print.tex
          latexmk -pdf web.tex
      
    - name: Send dispatch event on success
      if: success()
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "lean-build-success"}'
