name: Lean Build Check

on:
  push:
    branches: [ main, master ]
    paths:
      - 'lakefile.lean'
      - 'FinLin/**'
      - 'blueprint/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'lakefile.lean'
      - 'FinLin/**'
      - 'blueprint/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Lean
      run: |
        curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        source $HOME/.elan/env
        
    - name: Update dependencies
      run: lake update
      
    - name: Build project
      run: lake build
      
    - name: Build PDFs from LaTeX
      uses: xu-cheng/texlive-action@v2
      with:
        docker_image: ghcr.io/xu-cheng/texlive-full:20250101
        run: |
          cd blueprint/src
          latexmk -pdf print.tex
          latexmk -pdf web.tex
